"""Frozen file requests, one per operation.

No ``model`` on any of them, unlike every other capability: a file is not
generated by one and the endpoints take none. Carrying the field anyway would
invite a caller to set it and expect it to matter.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

__all__ = [
    "DeleteFileRequest",
    "DownloadFileRequest",
    "GetFileMetadataRequest",
    "ListFilesRequest",
    "UploadFileRequest",
]


@dataclass
class UploadFileRequest:
    filename: str = ""
    #: BYTES, where the reference takes a PHP string. A PHP string is a byte
    #: array, so the two agree in practice; ``bytes`` here says so in the type
    #: rather than leaving a caller to pass ``str`` and lose a PDF to an
    #: encoding step.
    content: bytes = b""
    mime_type: str | None = None
    provider_key: str = ""
    client_options: dict[str, Any] = field(default_factory=dict)
    provider_options: dict[str, Any] = field(default_factory=dict)


@dataclass
class ListFilesRequest:
    limit: int | None = None
    after_id: str | None = None
    #: Carried, and NOT sent to OpenAI, because OpenAI's files endpoint has no
    #: ``before`` parameter -- only ``after``. Kept on the request because the
    #: reference has it and a provider that paginates both ways can read it;
    #: dropping it belongs in the mapper, not here.
    before_id: str | None = None
    provider_key: str = ""
    client_options: dict[str, Any] = field(default_factory=dict)
    provider_options: dict[str, Any] = field(default_factory=dict)


@dataclass
class _FileIdRequest:
    """The three requests that are nothing but an id.

    They differ in which method takes them, not in what they hold, so the
    fields are declared once and the three names below are the distinction.
    """

    file_id: str = ""
    provider_key: str = ""
    client_options: dict[str, Any] = field(default_factory=dict)
    provider_options: dict[str, Any] = field(default_factory=dict)


@dataclass
class GetFileMetadataRequest(_FileIdRequest):
    pass


@dataclass
class DeleteFileRequest(_FileIdRequest):
    pass


@dataclass
class DownloadFileRequest(_FileIdRequest):
    pass
